// <auto-generated />
namespace PRSWebAppBackEndProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedVendorAttributes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedVendorAttributes));
        
        string IMigrationMetadata.Id
        {
            get { return "201803121343258_Added Vendor Attributes []"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
